/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:btnCloseMinimize:294590:
  println("btnClose - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btnCloseMinimize:294590:

public void button1_click2(GButton source, GEvent event) { //_CODE_:btnBlack:310389:
  println("btnBlack - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btnBlack:310389:

public void button2_click1(GButton source, GEvent event) { //_CODE_:btnTempDetect:906359:
  println("btnTempDetect - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btnTempDetect:906359:

public void button1_click3(GButton source, GEvent event) { //_CODE_:btnSolidColor:950586:
  println("btnSolidColor - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btnSolidColor:950586:

public void button1_click4(GButton source, GEvent event) { //_CODE_:btnScreen:626262:
  println("btnScreen - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btnScreen:626262:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.GREEN_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("LED Control");
  btnCloseMinimize = new GButton(this, 10, 260, 90, 40);
  btnCloseMinimize.setText("Close / Minimize");
  btnCloseMinimize.setTextBold();
  btnCloseMinimize.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  btnCloseMinimize.addEventHandler(this, "button1_click1");
  btnBlack = new GButton(this, 10, 200, 90, 40);
  btnBlack.setText("Off (Black)");
  btnBlack.setTextBold();
  btnBlack.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  btnBlack.addEventHandler(this, "button1_click2");
  btnTempDetect = new GButton(this, 10, 80, 90, 40);
  btnTempDetect.setText("GPUTemp");
  btnTempDetect.setTextBold();
  btnTempDetect.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  btnTempDetect.addEventHandler(this, "button2_click1");
  btnSolidColor = new GButton(this, 10, 140, 90, 40);
  btnSolidColor.setText("Solid Color");
  btnSolidColor.setTextBold();
  btnSolidColor.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  btnSolidColor.addEventHandler(this, "button1_click3");
  btnScreen = new GButton(this, 10, 20, 90, 40);
  btnScreen.setText("Computer Screen");
  btnScreen.setTextBold();
  btnScreen.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  btnScreen.addEventHandler(this, "button1_click4");
}

// Variable declarations 
// autogenerated do not edit
GButton btnCloseMinimize; 
GButton btnBlack; 
GButton btnTempDetect; 
GButton btnSolidColor; 
GButton btnScreen; 